# Permalinks
permalink:           pretty

# Setup
title:               Temitope Adeyemi
tagline:             Data Analyst
url:                 https://diamondtee.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            compressed

# About/contact
author:
  name:              Temitope Adeyemi
  url:               diamondtee.github.io
  email:             adeyemitemitope2018@gmail.com

# Custom vars
version:             2.0.1
github:
  repo:              https://github.com/diamondtee
google_analytics:    UA-3363703-15
twitter:             biggysmall44
github:              diamondtee
dribbble:            jamigibbs

# Gems
plugins:
  # - jekyll-paginate
  # - jekyll-gist
